version: '3.8'

services:
  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongo_pizza
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-pizza}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-pizza} 
      MONGO_INITDB_DATABASE: ${DB_NAME:-pizza}
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - ./docker/mongodata:/data/db
    command: --auth
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq_pizza
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME:-pizza}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS:-pizza}
    ports:
      - ${MQ_PORT:-5672}:5672
      - ${MQ_PORT:-15672}:15672
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    